### ISSUE TITLE
heartbeatが動いていない

### ISSUE THREAD

**Issue by akomekagome** [tasuren/niconico_dl#2]
初めまして、Akomeと申します！
個人でニコニコ動画を流せるdiscord音楽botを開発していて、そこでこのライブリを使わせていただいたのですが、heartbeatに関して気になるところがいくつかあったのでissue立てさせていただきました！

## heartbeatが動いていない
niconico_dl_asyncの方なのですが、コードを追ってみてもheartbeatが動いていると思えませんでした。
実際、get_download_link()で取得したurlも一定時間後に403エラーが帰ってくる状況でした。

## heartbeatで一部よくわからない処理がある。

https://github.com/tasuren/niconico_dl/blob/84b8d1e0bbdb353876485c713aa03b33b10370e1/niconico_dl_async/__init__.py#L142-L173
こちらの部分なのですが、151から162行目以外の処理の意味がわかりませんでした。
自分のこちらの[Fork](https://github.com/akomekagome/niconico-dl)で僭越ながらいじらせていただいたのですが、151~162行目の処理だけで問題なく動いているようでした。自分が気づけていない意図がありましたら申し訳ないです。

**Comment by tasuren** [comment]
コメントとPRありがとうございます。
ずっと前から忙しく放置してました...
了解です。時間があれば詳しく見てみたいと思います。
そしてまだまだPythonが未熟なころに作ったものなのでいつかコードを書き直したいと思います。

151~162の箇所はニコニコ動画の通信の仕様上必要な箇所です。
ニコニコ動画から動画を取得する際は定期的に`https://api.dmc.nico/api/sessions/{session_id}?_format=json&_method=PUT`に動画データを送らなければ通信が切れてしまいます。
これをしている箇所です。
(niconico_dlを作ろうと思った時の仕様で今の仕様もこの仕様かは不明です。)

**Comment by akomekagome** [comment]
分かりにくいissueで申し訳ないです！
おっしゃる通り151~162行目の部分は必要な部分だと思いますが、それ以外の部分の意味が分からなかったため質問させていただいたきました。

自分の音楽botも151~162行目の処理だけで動いているので、特に仕様の変更はないと思います！

**Comment by y-chan** [comment]
async版のheartbeatに関してですが、まだ私自身も試したわけではないのでうまくいく確証はありませんが、`asyncio.gather`をうまく使えば、heartbeatを動かしながらプログラム内でのダウンロードができると思います(現状のコードは、heartbeatを動かしてクライアントが生きていることを示し続ける代わりに手動ダウンロードする形になっているという認識ですがあってますかね...?)。

**Comment by tasuren** [comment]
> async版のheartbeatに関してですが、まだ私自身も試したわけではないのでうまくいく確証はありませんが、`asyncio.gather`をうまく使えば、heartbeatを動かしながらプログラム内でのダウンロードができると思います(現状のコードは、heartbeatを動かしてクライアントが生きていることを示し続ける代わりに手動ダウンロードする形になっているという認識ですがあってますかね...?)。

@y-chan 
すみません返信するの忘れてました。
そしてまたすみません書き直す前の状態がどんなのか忘れたのですぐには返信できません。
書き直し後は`heartbeat`を`loop.create_task`で動かしています。

@akomekagome 
コードを書き直して動くことを確認したので恐らく動くと思います。

**Comment by tasuren** [comment]
今日リリースしたバージョンでうまく動くのを確認したのでcloseします。
