### ISSUE TITLE
提案: Type Hintsの追加

### ISSUE THREAD

**Issue by y-chan** [tasuren/niconico_dl#3]
初めまして。y-chanといいます。
ニコニコ動画の仕様変更に対応したダウンローダーを探していたところ、こちらにたどり着き、コードを読み、参考にさせていただいています。

さて、本題ですが、PythonにはType Hintsという仕組みがあります。
Type Hintsを使えば動的型付けのPythonでありながら、それなりに型安全なコード(もちろん完全とは言えませんが)を書くことが出来、IDEなどでの補完も充実するようになります。
また、可読性も向上します。
以下は例です
```
def x_plus_y(x: int, y: int) -> int:
    return x + y
```

私の方でType Hintsを実装し、PRしようかと思っていますが、必要がなければIssueはcloseします。

**Comment by tasuren** [comment]
了解です。
自分はいつか時間がある時にこのコードを書き直す予定なのでその時にTypeHintsをやろうと思います。
PRを出してくれるともちろん嬉しいです。

**Comment by tasuren** [comment]
結構できてきました。
型ヒントをつけてみたのですがどうでしょうか？
rewriteブランチにあります。

**Comment by y-chan** [comment]
良いと思います！
dictに関してはさらに詳細なTypeDictという定義を作ることができます。
これを作るのは非常に面倒だと思いますし、こちらで作りかけていたものがあるので、PRさせてもらいますね。

**Comment by tasuren** [comment]
ありがとうございます！
了解です。

**Comment by tasuren** [comment]
`TypedDict`以外はほとんど実装することができました！

**Comment by tasuren** [comment]
@y-chan 
 現在の`niconico_dl`のコードはあまり良いコードと言えなく書き直したいのと、クッキーを使ったログインが必要なAPIへのリクエストなどもしたいのでニコニコ全体を対象とした`niconico.py`というライブラリを作りたいと思います。
そこでは動画のダウンロード以外にもマイリスト取得なども作り型補完がしっかり効くようにしたいと思います。

リポジトリ：https://github.com/tasuren/niconico.py

**Comment by tasuren** [comment]
@y-chan 
niconico.pyでダウンロードとマイリストの取得ができるようにし、pypiにリリースをしました。  
また、大体の型ヒントをつけています。
(不完全ですが動画タイトル等の最低限のものは実装済みです。)
https://github.com/tasuren/niconico.py  

それともうniconico_dlの開発はしないため、このリポジトリは後日アーカイブします。
