### ISSUE TITLE
提案:mylist取得機能の追加

### ISSUE THREAD

**Issue by Marusoftware** [tasuren/niconico_dl#7]
あと、この機能があると素晴らしく使いやすいな...と単純におもったので...
提案させていただきました...

**Comment by tasuren** [comment]
了解です。

**Comment by Marusoftware** [comment]
ありがとうございます。
よろしくお願いします。
(なにかAPIがあれば、PR送りたいのですが...)

**Comment by tuna2134** [comment]
mylistとは？

**Comment by tasuren** [comment]
> mylistとは？

YouTubeで言う再生リストです。

**Comment by tasuren** [comment]
@Marusoftware
クッキー等の実装などもする必要があり現在のniconico_dlの構造だと少し良いコードと言えない状態となってしまいます。  
ですので`niconico.py`という名前で新しくニコニコ動画全体のためのライブラリを作りたいと思います。
この`niconico.py`でマイリストもサポートしたいと思います。

新しいリポジトリ：https://github.com/tasuren/niconico.py

**Comment by tasuren** [comment]
@Marusoftware

マイリストを取得することができる新しいニコニコ動画用のライブラリをリリースしました。
そしてniconico_dlの開発は停止してniconico.pyを開発したいと思います。
よってniconico_dlのリポジトリは後日アーカイブします。

新しいniconico.py：https://github.com/tasuren/niconico.py
